name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build zana service
      working-directory: services/zana
      run: cargo build --verbose
    - name: Run tests in zana service
      working-directory: services/zana
      run: cargo test --verbose
    - name: Build zana_lambda service
      working-directory: services/zana_lambda
      run: cargo build --verbose
    - name: Run tests in zana_lambda service
      working-directory: services/zana_lambda
      run: cargo test --verbose
