name: release

on:
  workflow_run:
    workflows: [ "deploy" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && !startsWith(github.event.head_commit.message, 'doc:') && !startsWith(github.event.head_commit.message, 'format:') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Setup Rust and NodeJS
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Node.js toolchain
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Read version from version file
      - name: Read version
        id: read_version
        run: echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
      # Create and push new tag
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            const version = '${{ steps.read_version.outputs.version }}';
            const tag = `v${version}`;
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: context.sha
            });
      # Create new release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.read_version.outputs.version }}

      # Update version
      - if: ${{ startsWith(github.event.head_commit.message, 'feat:') }}
        name: Update minor version
        working-directory: tools/release
        run: npm install && npm run release:minor
      - if: ${{ !startsWith(github.event.head_commit.message, 'feat:') }}
        name: Update patch version
        working-directory: tools/release
        run: npm install && npm run release:patch
      # Commit the changes
      - name: Commit version changes
        run: |
          git config --global user.name 'Kushtrim Hajrizi'
          git config --global user.email 'kushtrimh@users.noreply.github.com'
          git commit -am "release: version update"
          git push
